context:
  version: "3.11.2"

package:
  name: apscheduler
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/a/APScheduler/apscheduler-${{ version }}.tar.gz
  sha256: 2a9966b052ec805f020c8c4c3ae6e6a06e24b1bf19f2e11d91d8cca0473eef41

build:
  number: 0
  noarch: python
  script: python -m pip install . -vv --no-build-isolation --no-deps

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools >=64
    - setuptools_scm >=6.4
  run:
    - python >=${{ python_min }}
    - tzlocal >=3.0

tests:
  - python:
      imports:
        - apscheduler
        - apscheduler.executors
        - apscheduler.jobstores
        - apscheduler.schedulers
        - apscheduler.schedulers.blocking
        - apscheduler.triggers
        - apscheduler.triggers.cron
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  license: MIT
  license_file: LICENSE.txt
  summary: In-process task scheduler with Cron-like capabilities
  homepage: https://github.com/agronholm/apscheduler
  repository: https://github.com/agronholm/apscheduler
  documentation: https://apscheduler.readthedocs.io

extra:
  recipe-maintainers:
    - ddunwoody
    - synapticarbors
